#version 460

#extension GL_GOOGLE_include_directive  : enable                    /* @brief Enable include Macro.           */
#include "Header/ShaderCommon.h"
#include "Header/ShaderPreRendererLayout.glsl"

layout(set = 2, binding = 0, rgba8) uniform image2D SceneColor;    /* @brief SceneColor. */

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

void main()
{
	imageStore(SceneColor, ivec2(gl_GlobalInvocationID.xy), vec4(1.0f, 0.0f, 0.0f, 1.0f));
}