#version 460

#extension GL_GOOGLE_include_directive  : enable                    /* @brief Enable include Macro.           */
#include "Header/ShaderCommon.h"
#include "Header/ShaderPreRendererLayout.glsl"

layout(set = 2, binding = 0, rgba8) uniform image2D SceneColor;    /* @brief SceneColor. */

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

const float s_coeffs[5] = float[](0.23583300411701202392578125, 0.19806300103664398193359375, 0.11729399859905242919921875, 0.0489679984748363494873046875, 0.014407999813556671142578125);

const vec2 u_dir = vec2(0.0333333f, 0.0f);

void main()
{
	int s_lenght = 5;
    vec4 accum = imageLoad(SceneColor, ivec2(gl_GlobalInvocationID.xy)) * s_coeffs[0];
    for (int i = 1; i < s_lenght; i++)
    {
        float f = float(i);
        accum += imageLoad(SceneColor, ivec2(gl_GlobalInvocationID.xy + u_dir * view.sceneTextureSize.xy * f)) * s_coeffs[i];
        accum += imageLoad(SceneColor, ivec2(gl_GlobalInvocationID.xy - u_dir * view.sceneTextureSize.xy * f)) * s_coeffs[i];
    }
    
    //memoryBarrier();

    //imageStore(SceneColor, ivec2(gl_GlobalInvocationID.xy), accum);
}