/**
* @file Shader.PostProcessRenderer.Blur.Default.comp.
* @brief This Shader Defines PostProcessRenderer SubPass Blur Default Compute Shader Behaves.
* @author Spices.
*/

/************************************Pre Compile*******************************************/

#version 460

#extension GL_GOOGLE_include_directive             : enable            /* @brief Enable include Macro.            */
#extension GL_KHR_shader_subgroup_clustered        : enable            /* @brief Enable subgroup cluster feature. */

#include "Header/ShaderCommon.h"
#include "Header/ShaderPreRendererLayout.glsl"

/*****************************************************************************************/

/*************************************Comp Input******************************************/

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

/*****************************************************************************************/

/************************************Specific Data****************************************/

layout(set = 2, binding = 0, rgba8) uniform image2D SceneColor;    /* @brief SceneColor. */

/*****************************************************************************************/

/************************************Constant Data****************************************/

//const int s_lenght = 3;  float s_coeffs[] = { 0.382971, 0.241842, 0.060654, }; // norm = 0.987962
//const int s_lenght = 4;  float s_coeffs[] = { 0.292360, 0.223596, 0.099952, 0.026085, }; // norm = 0.991625
const int s_lenght = 5;  float s_coeffs[] = { 0.235833, 0.198063, 0.117294, 0.048968, 0.014408, }; // norm = 0.993299
//const int s_lenght = 6;  float s_coeffs[] = { 0.197419, 0.174688, 0.121007, 0.065615, 0.027848, 0.009250, }; // norm = 0.994236
//const int s_lenght = 7;  float s_coeffs[] = { 0.169680, 0.155018, 0.118191, 0.075202, 0.039930, 0.017692, 0.006541, }; // norm = 0.994827
//const int s_lenght = 8;  float s_coeffs[] = { 0.148734, 0.138756, 0.112653, 0.079592, 0.048936, 0.026183, 0.012191, 0.004939, }; // norm = 0.995231
//const int s_lenght = 9;  float s_coeffs[] = { 0.132370, 0.125285, 0.106221, 0.080669, 0.054877, 0.033440, 0.018252, 0.008924, 0.003908, }; // norm = 0.995524
//const int s_lenght = 10; float s_coeffs[] = { 0.119237, 0.114032, 0.099737, 0.079779, 0.058361, 0.039045, 0.023890, 0.013368, 0.006841, 0.003201, }; // norm = 0.995746
//const int s_lenght = 11; float s_coeffs[] = { 0.108467, 0.104534, 0.093566, 0.077782, 0.060053, 0.043061, 0.028677, 0.017737, 0.010188, 0.005435, 0.002693, }; // norm = 0.995919
//const int s_lenght = 12; float s_coeffs[] = { 0.099477, 0.096435, 0.087850, 0.075206, 0.060500, 0.045736, 0.032491, 0.021690, 0.013606, 0.008021, 0.004443, 0.002313, }; // norm = 0.996058
//const int s_lenght = 13; float s_coeffs[] = { 0.091860, 0.089459, 0.082622, 0.072368, 0.060113, 0.047355, 0.035378, 0.025065, 0.016842, 0.010732, 0.006486, 0.003717, 0.002020, }; // norm = 0.996172
//const int s_lenght = 14; float s_coeffs[] = { 0.085325, 0.083397, 0.077868, 0.069455, 0.059181, 0.048172, 0.037458, 0.027824, 0.019744, 0.013384, 0.008667, 0.005361, 0.003168, 0.001789, }; // norm = 0.996267
//const int s_lenght = 15; float s_coeffs[] = { 0.079656, 0.078085, 0.073554, 0.066578, 0.057908, 0.048399, 0.038870, 0.029997, 0.022245, 0.015852, 0.010854, 0.007142, 0.004516, 0.002743, 0.001602, }; // norm = 0.996347
//const int s_lenght = 16; float s_coeffs[] = { 0.074693, 0.073396, 0.069638, 0.063796, 0.056431, 0.048197, 0.039746, 0.031648, 0.024332, 0.018063, 0.012947, 0.008961, 0.005988, 0.003864, 0.002407, 0.001448, }; // norm = 0.996416

/*****************************************************************************************/

/******************************************Functions**************************************/

/**
* @brief Apply blur effect with specific direction.
* @param[in] dir Blur direction.
*/
void DirectionalBlur(const in ivec2 dir);

/*****************************************************************************************/

/**********************************Shader Entry*******************************************/

void main()
{
    /**
    * @brief Horizontal blur.
    */
    //DirectionalBlur(ivec2(1, 0));

    /**
    * @brief Vertical blur.
    */ 
    //DirectionalBlur(ivec2(0, 1));
    

     //  x  0  1  2  3  4  5  6  7
     // y+------------------------
     // 0|  0  1  8  9 16 17 24 25
     // 1|  2  3 10 11 18 19 26 27
     // 2|  4  5 12 13 20 21 28 29
     // 3|  6  7 14 15 22 23 30 31
    
    
    uint numClusters = gl_SubgroupSize / 4;           // 8
    uint clusterID = gl_SubgroupInvocationID / 4;     // 0 - 7

    uint x = ((clusterID / 2) * 2) + (gl_SubgroupInvocationID % 2);   // [0, 1, 0, 1], [0, 1, 0, 1], [2, 3, 2, 3], [2, 3, 2, 3], [4, 5, 4, 5], [4, 5, 4, 5], [6, 7, 6, 7], [6, 7, 6, 7]
    uint y = (gl_SubgroupInvocationID / 2) % 4;                       // [0, 0, 1, 1], [2, 2, 3, 3], [0, 0, 1, 1], [2, 2, 3, 3], [0, 0, 1, 1], [2, 2, 3, 3], [0, 0, 1, 1], [2, 2, 3, 3]

                                       // 32
    uvec3 inIndex = gl_WorkGroupID * uvec3(numClusters, 4, 1) + uvec3(x, y, 1);

    vec4 load = imageLoad(SceneColor, ivec2(inIndex.xy));

    vec4 max  = subgroupClusteredMax(load, 4);

    //if (0 == (gl_SubgroupInvocationID % 4))
    //{
    //    uvec3 outIndex = gl_WorkGroupID * gl_WorkGroupSize + uvec3(x, y, 1);
    //
    //    imageStore(SceneColor, ivec2(outIndex.xy), vec4(1.0f));
    //}

    imageStore(SceneColor, ivec2(gl_GlobalInvocationID.xy), vec4(vec3(gl_SubgroupInvocationID), 1.0f));
}

/*****************************************************************************************/

void DirectionalBlur(const in ivec2 dir)
{
    vec4 accum = imageLoad(SceneColor, ivec2(gl_GlobalInvocationID.xy)) * s_coeffs[0];
    for (int i = 1; i < s_lenght; i++)
    {
        accum += imageLoad(SceneColor, ivec2(gl_GlobalInvocationID.xy + dir * i)) * s_coeffs[i];
        accum += imageLoad(SceneColor, ivec2(gl_GlobalInvocationID.xy - dir * i)) * s_coeffs[i];
    }
    
    // Wait for read.
    memoryBarrierImage();
    
    imageStore(SceneColor, ivec2(gl_GlobalInvocationID.xy), accum);
    
    // Wait for write.
    memoryBarrierImage();
}