/**
* @file Shader.PostProcessRenderer.TAA.Default.comp.
* @brief This Shader Defines PostProcessRenderer SubPass TAA Default Compute Shader Behaves.
* @author Spices.
*/

/************************************Pre Compile*******************************************/

#version 460

#extension GL_GOOGLE_include_directive             : enable            /* @brief Enable include Macro.            */

#include "Header/ShaderCommon.h"
#include "Header/ShaderPreRendererLayout.glsl"

/*****************************************************************************************/

/*************************************Comp Input******************************************/

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

/*****************************************************************************************/

/************************************Specific Data****************************************/



/*****************************************************************************************/

/*********************************Push Constant*******************************************/



/*****************************************************************************************/

/************************************Constant Data****************************************/

const int RADIUS        = 1;
const int GROUP_SIZE    = 32;
const int TILE_DIM      = (2 * RADIUS + GROUP_SIZE);

shared vec3 Tile[TILE_DIM * TILE_DIM];

/*****************************************************************************************/

/**********************************Shader Entry*******************************************/

void main()
{
   /**const ivec2 dims      = ivec2(view.sceneTextureSize.x, view.sceneTextureSize.y);
   const vec2 texelSize  = view.sceneTextureSize.zw;
   bool isSkyPixel;

   const vec2 uv       = (gl_GlobalInvocationID.xy + 0.5f) * texelSize;
   const vec2 tilePos  = gl_LocalInvocationID.xy + RADIUS + 0.5f;

   if (gl_LocalInvocationIDLinear < TILE_DIM * TILE_DIM / 4)
   {
       const int2 anchor = groupID.xy * GROUP_SIZE - RADIUS;

   }*/
}

/*****************************************************************************************/