name: CI for SpicesEngine Solution

on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate Solution
      run: call .\Startup.bat

    - name: Build Solution
      run: call .\Scripts\Build_Debug_x64.bat